config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  #delete 'restaurants/:id', to: 'restaurants#destroy', as: 'wtf'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  # validates :name, uniqueness: true, presence: true
  validates :name, :address, :phone_number, :category, presence: true
  validates :category, inclusion:
  { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, :content, presence: true
  validates :rating, presence: true, inclusion:
  { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show

  end

  def new
    #render and empty form, send an empty restaurant object
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
    #create a Restaurant object
    #make it presistant
  end

  def edit
    #render a form with the existing object
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
    #make changes presistant
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
    #destroy one Restaurant object
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:address, :name, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    # we need @restaurant in our `simple_form_for`
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name, 'Please enter a name' %>
  <%= f.text_field :name %>
  <%= f.label :address, 'Please enter an address' %>
  <%= f.text_field :address %>
  <%= f.label :phone_number, 'Please enter a phone number' %>
  <%= f.text_field :phone_number %>
  <%= f.label :category, 'Please enter a category' %>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>List of all Restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <p><%= restaurant.address %></p>
  <%= link_to "see details", restaurant_path(restaurant), class: "btn btn-primary" %>
<% end %>
<br>
<%= link_to "Add a new Restaurant", new_restaurant_path, class: "btn btn-primary" %>

app/views/restaurants/new.html.erb
<%= render 'form'%>
<%= link_to 'back to restaurants', restaurants_path, class: "btn btn-primary" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><% @restaurant.reviews.each do |review| %></p>
  <p><%= review.content %></p>
  <p><%= review.rating %></p>
<% end %>
<br>
<%= link_to 'Delete this', restaurant_path(@restaurant.id), method: :delete %>


<%= link_to 'add a review', new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
<%= link_to 'back to restaurants', restaurants_path, class: "btn btn-primary" %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, as: :integer %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>
<br>
<%= link_to 'back to restaurants', restaurants_path, class: "btn btn-primary" %>